name: ci

on:
  push:
    branches:
      - main
  pull_request:

env:
    DATABASE_URL: ${{ secrets.DATABASE_URL }}

jobs:
  ci:
    name: ci
    runs-on: ubuntu-latest
    services:
      postgres:
        image: postgres:15
        env:
          POSTGRES_USER: ${{ secrets.POSTGRES_USER }}
          POSTGRES_PASSWORD: ${{ secrets.POSTGRES_PASSWORD }}
          POSTGRES_DB: ${{ secrets.POSTGRES_DB }}
        ports:
          - 5432:5432
        options: >-
          --health-cmd pg_isready
          --health-interval 10s
          --health-timeout 5s
          --health-retries 5


    steps:
      - uses: actions/checkout@v2

      - name: Setup pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 9.7.1

      - name: Cache dependencies
        uses: actions/cache@v2
        with:
          path: "**/node_modules"
          key: ${{ runner.os }}-modules-${{ hashFiles('**/pnpm-lock.yaml') }}

      - name: Install dependencies
        run: pnpm i

      - name: Load Schema
        run: psql ${{ secrets.DATABASE_URL }} < db/schema.sql

      - name: Generate Prisma Client & GraphQL Types
        run: pnpm gen

      - name: Build
        run: pnpm build

      - name: Run tests
        run: pnpm test

      - name: Run linter
        run: pnpm lint
